CREATE USER aq_admin IDENTIFIED BY WElcome##123 DEFAULT TABLESPACE users TEMPORARY TABLESPACE temp;
ALTER USER aq_admin QUOTA UNLIMITED ON users;
GRANT aq_administrator_role TO aq_admin;
GRANT connect TO aq_admin;
GRANT create type TO aq_admin;


CREATE USER aq_user IDENTIFIED BY WElcome##123 DEFAULT TABLESPACE users TEMPORARY TABLESPACE temp;
--grant roles to aq_user
GRANT aq_user_role TO aq_user; 



CREATE USER "SRC_OCIGGLL" IDENTIFIED BY "WElcome##123";

GRANT CREATE SESSION TO "SRC_OCIGGLL";

ALTER USER "SRC_OCIGGLL" ACCOUNT UNLOCK;

GRANT CONNECT, RESOURCE  TO "SRC_OCIGGLL";

GRANT UNLIMITED TABLESPACE TO "SRC_OCIGGLL";



--------------------------------------------------------
--  File created - @dsgray 3-07-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SRC_CITY
--------------------------------------------------------

  CREATE TABLE "SRC_OCIGGLL"."SRC_CITY" 
   (	"CITY_ID" NUMBER(10,0), 
	"CITY" VARCHAR2(50 BYTE), 
	"REGION_ID" NUMBER(10,0), 
	"POPULATION" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Table SRC_CUSTOMER
--------------------------------------------------------

  CREATE TABLE "SRC_OCIGGLL"."SRC_CUSTOMER" 
   (	"CUSTID" NUMBER(10,0), 
	"DEAR" NUMBER(1,0), 
	"LAST_NAME" VARCHAR2(50 BYTE), 
	"FIRST_NAME" VARCHAR2(50 BYTE), 
	"ADDRESS" VARCHAR2(100 BYTE), 
	"CITY_ID" NUMBER(10,0), 
	"PHONE" VARCHAR2(50 BYTE), 
	"AGE" NUMBER(3,0), 
	"SALES_PERS_ID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Table SRC_ORDERS
--------------------------------------------------------

  CREATE TABLE "SRC_OCIGGLL"."SRC_ORDERS" 
   (	"ORDER_ID" NUMBER(10,0), 
	"STATUS" VARCHAR2(3 BYTE), 
	"CUST_ID" NUMBER(10,0), 
	"ORDER_DATE" DATE, 
	"CUSTOMER" VARCHAR2(35 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Table SRC_ORDER_LINES
--------------------------------------------------------

  CREATE TABLE "SRC_OCIGGLL"."SRC_ORDER_LINES" 
   (	"ORDER_ID" NUMBER(10,0), 
	"LORDER_ID" NUMBER(10,0), 
	"PRODUCT_ID" NUMBER(10,0), 
	"QTY" NUMBER(10,0), 
	"AMOUNT" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Table SRC_PRODUCT
--------------------------------------------------------

  CREATE TABLE "SRC_OCIGGLL"."SRC_PRODUCT" 
   (	"PRODUCT_ID" NUMBER(10,0), 
	"PRODUCT" VARCHAR2(50 BYTE), 
	"PRICE" NUMBER(10,2), 
	"FAMILY_NAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Table SRC_REGION
--------------------------------------------------------

  CREATE TABLE "SRC_OCIGGLL"."SRC_REGION" 
   (	"REGION_ID" NUMBER(10,0), 
	"REGION" VARCHAR2(50 BYTE), 
	"COUNTRY_ID" NUMBER(10,0), 
	"COUNTRY" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
Insert into SRC_OCIGGLL.SRC_CITY (CITY_ID,CITY,REGION_ID,POPULATION) values (10,'Houston',20,743113);
Insert into SRC_OCIGGLL.SRC_CITY (CITY_ID,CITY,REGION_ID,POPULATION) values (11,'Dallas',20,822416);
Insert into SRC_OCIGGLL.SRC_CITY (CITY_ID,CITY,REGION_ID,POPULATION) values (12,'San Francisco',21,157574);
Insert into SRC_OCIGGLL.SRC_CITY (CITY_ID,CITY,REGION_ID,POPULATION) values (13,'Los Angeles',21,743878);
Insert into SRC_OCIGGLL.SRC_CITY (CITY_ID,CITY,REGION_ID,POPULATION) values (14,'San Diego',21,840689);
Insert into SRC_OCIGGLL.SRC_CITY (CITY_ID,CITY,REGION_ID,POPULATION) values (15,'Chicago',23,616472);
Insert into SRC_OCIGGLL.SRC_CITY (CITY_ID,CITY,REGION_ID,POPULATION) values (16,'Memphis',23,580075);
Insert into SRC_OCIGGLL.SRC_CITY (CITY_ID,CITY,REGION_ID,POPULATION) values (107,'New York City',22,124434);
Insert into SRC_OCIGGLL.SRC_CITY (CITY_ID,CITY,REGION_ID,POPULATION) values (18,'Boston',22,275581);
Insert into SRC_OCIGGLL.SRC_CITY (CITY_ID,CITY,REGION_ID,POPULATION) values (19,'Washington D.C.',22,688002);
Insert into SRC_OCIGGLL.SRC_CITY (CITY_ID,CITY,REGION_ID,POPULATION) values (20,'Paris',310,74780);
Insert into SRC_OCIGGLL.SRC_CITY (CITY_ID,CITY,REGION_ID,POPULATION) values (21,'Versailles',30,625097);
Insert into SRC_OCIGGLL.SRC_CITY (CITY_ID,CITY,REGION_ID,POPULATION) values (22,'Fontainebleau',30,285559);
Insert into SRC_OCIGGLL.SRC_CITY (CITY_ID,CITY,REGION_ID,POPULATION) values (23,'Lyon',31,689978);
Insert into SRC_OCIGGLL.SRC_CITY (CITY_ID,CITY,REGION_ID,POPULATION) values (24,'Grenoble',31,488825);
Insert into SRC_OCIGGLL.SRC_CITY (CITY_ID,CITY,REGION_ID,POPULATION) values (25,'Albertville',31,959909);
Insert into SRC_OCIGGLL.SRC_CITY (CITY_ID,CITY,REGION_ID,POPULATION) values (27,'Nice',32,482282);
Insert into SRC_OCIGGLL.SRC_CITY (CITY_ID,CITY,REGION_ID,POPULATION) values (28,'Marseilles',32,702646);
Insert into SRC_OCIGGLL.SRC_CITY (CITY_ID,CITY,REGION_ID,POPULATION) values (29,'Bordeaux',32,898032);
Insert into SRC_OCIGGLL.SRC_CITY (CITY_ID,CITY,REGION_ID,POPULATION) values (30,'Swansea',40,788193);
Insert into SRC_OCIGGLL.SRC_CITY (CITY_ID,CITY,REGION_ID,POPULATION) values (31,'Glasgow',41,59540);
Insert into SRC_OCIGGLL.SRC_CITY (CITY_ID,CITY,REGION_ID,POPULATION) values (32,'Edinburgh',41,952500);
Insert into SRC_OCIGGLL.SRC_CITY (CITY_ID,CITY,REGION_ID,POPULATION) values (33,'Belfast',42,715052);
Insert into SRC_OCIGGLL.SRC_CITY (CITY_ID,CITY,REGION_ID,POPULATION) values (34,'Londonderry',42,734127);
Insert into SRC_OCIGGLL.SRC_CITY (CITY_ID,CITY,REGION_ID,POPULATION) values (35,'London',43,69042);
Insert into SRC_OCIGGLL.SRC_CITY (CITY_ID,CITY,REGION_ID,POPULATION) values (36,'Oxford',43,270262);
Insert into SRC_OCIGGLL.SRC_CITY (CITY_ID,CITY,REGION_ID,POPULATION) values (37,'Manchester',43,455126);
Insert into SRC_OCIGGLL.SRC_CITY (CITY_ID,CITY,REGION_ID,POPULATION) values (38,'Cardiff',40,643);
Insert into SRC_OCIGGLL.SRC_CITY (CITY_ID,CITY,REGION_ID,POPULATION) values (40,'Amsterdam',51,522347);
Insert into SRC_OCIGGLL.SRC_CITY (CITY_ID,CITY,REGION_ID,POPULATION) values (41,'Utrecht',51,183244);
Insert into SRC_OCIGGLL.SRC_CITY (CITY_ID,CITY,REGION_ID,POPULATION) values (42,'Rotterdam',50,851329);
Insert into SRC_OCIGGLL.SRC_CITY (CITY_ID,CITY,REGION_ID,POPULATION) values (43,'Eindhoven',50,116158);
Insert into SRC_OCIGGLL.SRC_CITY (CITY_ID,CITY,REGION_ID,POPULATION) values (50,'Dusseldorf',60,999826);
Insert into SRC_OCIGGLL.SRC_CITY (CITY_ID,CITY,REGION_ID,POPULATION) values (51,'Cologne',60,502180);
Insert into SRC_OCIGGLL.SRC_CITY (CITY_ID,CITY,REGION_ID,POPULATION) values (52,'Munich',61,122893);
Insert into SRC_OCIGGLL.SRC_CITY (CITY_ID,CITY,REGION_ID,POPULATION) values (53,'Dresden',62,139454);
Insert into SRC_OCIGGLL.SRC_CITY (CITY_ID,CITY,REGION_ID,POPULATION) values (54,'Magdeburg',62,790080);
Insert into SRC_OCIGGLL.SRC_CITY (CITY_ID,CITY,REGION_ID,POPULATION) values (55,'Berlin',62,590032);
Insert into SRC_OCIGGLL.SRC_CITY (CITY_ID,CITY,REGION_ID,POPULATION) values (56,'Augsburg',61,912298);
Insert into SRC_OCIGGLL.SRC_CITY (CITY_ID,CITY,REGION_ID,POPULATION) values (60,'Sidney',70,890962);
Insert into SRC_OCIGGLL.SRC_CITY (CITY_ID,CITY,REGION_ID,POPULATION) values (61,'Canberra',70,353288);
Insert into SRC_OCIGGLL.SRC_CITY (CITY_ID,CITY,REGION_ID,POPULATION) values (62,'Melbourne',71,857478);
Insert into SRC_OCIGGLL.SRC_CITY (CITY_ID,CITY,REGION_ID,POPULATION) values (63,'Brisbane',72,505179);
Insert into SRC_OCIGGLL.SRC_CITY (CITY_ID,CITY,REGION_ID,POPULATION) values (64,'Gold Coast',72,575174);
Insert into SRC_OCIGGLL.SRC_CITY (CITY_ID,CITY,REGION_ID,POPULATION) values (70,'Tokyo',80,992823);
Insert into SRC_OCIGGLL.SRC_CITY (CITY_ID,CITY,REGION_ID,POPULATION) values (71,'Yokohama',80,725821);
Insert into SRC_OCIGGLL.SRC_CITY (CITY_ID,CITY,REGION_ID,POPULATION) values (72,'Osaka',81,501768);
Insert into SRC_OCIGGLL.SRC_CITY (CITY_ID,CITY,REGION_ID,POPULATION) values (73,'Kyoto',81,78899);
Insert into SRC_OCIGGLL.SRC_CITY (CITY_ID,CITY,REGION_ID,POPULATION) values (74,'Kobe',81,81758);
Insert into SRC_OCIGGLL.SRC_CITY (CITY_ID,CITY,REGION_ID,POPULATION) values (500,'Ecully',401,160994);
Insert into SRC_OCIGGLL.SRC_CITY (CITY_ID,CITY,REGION_ID,POPULATION) values (501,'Aix en Provence',404,334847);
commit;
REM INSERTING into SRC_OCIGGLL.SRC_CUSTOMER
SET DEFINE OFF;
Insert into SRC_OCIGGLL.SRC_CUSTOMER (CUSTID,DEAR,LAST_NAME,FIRST_NAME,ADDRESS,CITY_ID,PHONE,AGE,SALES_PERS_ID) values (101,0,'Brendt','Paul','10 Jasper Blvd.',107,'(212) 555 2146',19,10);
Insert into SRC_OCIGGLL.SRC_CUSTOMER (CUSTID,DEAR,LAST_NAME,FIRST_NAME,ADDRESS,CITY_ID,PHONE,AGE,SALES_PERS_ID) values (102,0,'McCarthy','Robin','27 Pasadena Drive',11,'(214) 555 3075',29,11);
Insert into SRC_OCIGGLL.SRC_CUSTOMER (CUSTID,DEAR,LAST_NAME,FIRST_NAME,ADDRESS,CITY_ID,PHONE,AGE,SALES_PERS_ID) values (103,0,'Travis','Peter','7835 Hartford Drive',12,'(510) 555 4448',34,12);
Insert into SRC_OCIGGLL.SRC_CUSTOMER (CUSTID,DEAR,LAST_NAME,FIRST_NAME,ADDRESS,CITY_ID,PHONE,AGE,SALES_PERS_ID) values (104,0,'Larson','Joe','87 Carmel Blvd.',13,'(213) 555 5095',45,13);
Insert into SRC_OCIGGLL.SRC_CUSTOMER (CUSTID,DEAR,LAST_NAME,FIRST_NAME,ADDRESS,CITY_ID,PHONE,AGE,SALES_PERS_ID) values (105,0,'Goldschmidt','Tony','91 Torre drive',14,'(619) 555 6529',55,20);
Insert into SRC_OCIGGLL.SRC_CUSTOMER (CUSTID,DEAR,LAST_NAME,FIRST_NAME,ADDRESS,CITY_ID,PHONE,AGE,SALES_PERS_ID) values (106,0,'Baker','William','2890 Grant Avenue',15,'(312) 555 7040',64,21);
Insert into SRC_OCIGGLL.SRC_CUSTOMER (CUSTID,DEAR,LAST_NAME,FIRST_NAME,ADDRESS,CITY_ID,PHONE,AGE,SALES_PERS_ID) values (107,0,'Swenson','Jack','64 Imagination Drive',19,'(202) 555 8125',74,22);
Insert into SRC_OCIGGLL.SRC_CUSTOMER (CUSTID,DEAR,LAST_NAME,FIRST_NAME,ADDRESS,CITY_ID,PHONE,AGE,SALES_PERS_ID) values (201,0,'Sartois','Jean','71 rue Rousseau',25,'79 23 26 23',19,30);
Insert into SRC_OCIGGLL.SRC_CUSTOMER (CUSTID,DEAR,LAST_NAME,FIRST_NAME,ADDRESS,CITY_ID,PHONE,AGE,SALES_PERS_ID) values (202,0,'Michaud','Philippe','197 impasse Renoir',23,'78 21 86 20',22,31);
Insert into SRC_OCIGGLL.SRC_CUSTOMER (CUSTID,DEAR,LAST_NAME,FIRST_NAME,ADDRESS,CITY_ID,PHONE,AGE,SALES_PERS_ID) values (203,0,'Robert','Christian','1rue Cezanne',208,'42 25 27 29',38,32);
Insert into SRC_OCIGGLL.SRC_CUSTOMER (CUSTID,DEAR,LAST_NAME,FIRST_NAME,ADDRESS,CITY_ID,PHONE,AGE,SALES_PERS_ID) values (204,1,'Martin','Christine','12 allee Victor Hugo',24,'25 26 46 26',42,40);
Insert into SRC_OCIGGLL.SRC_CUSTOMER (CUSTID,DEAR,LAST_NAME,FIRST_NAME,ADDRESS,CITY_ID,PHONE,AGE,SALES_PERS_ID) values (205,0,'Piaget','Luc','38 allee des Saules',29,'53 42 24 28',56,41);
Insert into SRC_OCIGGLL.SRC_CUSTOMER (CUSTID,DEAR,LAST_NAME,FIRST_NAME,ADDRESS,CITY_ID,PHONE,AGE,SALES_PERS_ID) values (206,1,'Gentil','Michele','17montee des Chenes',25,'65 62 26 13',67,11);
Insert into SRC_OCIGGLL.SRC_CUSTOMER (CUSTID,DEAR,LAST_NAME,FIRST_NAME,ADDRESS,CITY_ID,PHONE,AGE,SALES_PERS_ID) values (207,1,'Dupont','Marie-Chantale','37 rue Murat',20,'46 72 23 53',72,50);
Insert into SRC_OCIGGLL.SRC_CUSTOMER (CUSTID,DEAR,LAST_NAME,FIRST_NAME,ADDRESS,CITY_ID,PHONE,AGE,SALES_PERS_ID) values (301,1,'Edwards','Caroline','68 Downing Street',35,'243867945',18,51);
Insert into SRC_OCIGGLL.SRC_CUSTOMER (CUSTID,DEAR,LAST_NAME,FIRST_NAME,ADDRESS,CITY_ID,PHONE,AGE,SALES_PERS_ID) values (302,0,'Marlow','Justin','290 Yorkshire Drive',32,'653643634',29,52);
Insert into SRC_OCIGGLL.SRC_CUSTOMER (CUSTID,DEAR,LAST_NAME,FIRST_NAME,ADDRESS,CITY_ID,PHONE,AGE,SALES_PERS_ID) values (303,0,'Wilson','John','28 Sutton Row',33,'158746231',34,11);
Insert into SRC_OCIGGLL.SRC_CUSTOMER (CUSTID,DEAR,LAST_NAME,FIRST_NAME,ADDRESS,CITY_ID,PHONE,AGE,SALES_PERS_ID) values (304,0,'McCartney','George','45 Glenthorne Road',34,'323768678',47,11);
Insert into SRC_OCIGGLL.SRC_CUSTOMER (CUSTID,DEAR,LAST_NAME,FIRST_NAME,ADDRESS,CITY_ID,PHONE,AGE,SALES_PERS_ID) values (305,1,'Keegan','Hariett','10 Hamilton Park',35,'566344643',56,11);
Insert into SRC_OCIGGLL.SRC_CUSTOMER (CUSTID,DEAR,LAST_NAME,FIRST_NAME,ADDRESS,CITY_ID,PHONE,AGE,SALES_PERS_ID) values (306,1,'Jones','Mary','34 Apple Grove',36,'143546456',68,31);
Insert into SRC_OCIGGLL.SRC_CUSTOMER (CUSTID,DEAR,LAST_NAME,FIRST_NAME,ADDRESS,CITY_ID,PHONE,AGE,SALES_PERS_ID) values (307,2,'Hopkins','Priscilla','The Gables',38,'634634643',73,302);
Insert into SRC_OCIGGLL.SRC_CUSTOMER (CUSTID,DEAR,LAST_NAME,FIRST_NAME,ADDRESS,CITY_ID,PHONE,AGE,SALES_PERS_ID) values (401,2,'Diemers','Erika','Wiesenstra� 40',51,'235345',18,40);
Insert into SRC_OCIGGLL.SRC_CUSTOMER (CUSTID,DEAR,LAST_NAME,FIRST_NAME,ADDRESS,CITY_ID,PHONE,AGE,SALES_PERS_ID) values (402,0,'Schiller','Jurgen','Auf dem Rain 4',52,'142352',24,41);
Insert into SRC_OCIGGLL.SRC_CUSTOMER (CUSTID,DEAR,LAST_NAME,FIRST_NAME,ADDRESS,CITY_ID,PHONE,AGE,SALES_PERS_ID) values (403,0,'Durnstein','Adolph','Thomashof 22',53,'745464',36,101);
Insert into SRC_OCIGGLL.SRC_CUSTOMER (CUSTID,DEAR,LAST_NAME,FIRST_NAME,ADDRESS,CITY_ID,PHONE,AGE,SALES_PERS_ID) values (404,0,'Weimar','Hans','Goethering 33',54,'346636',45,50);
Insert into SRC_OCIGGLL.SRC_CUSTOMER (CUSTID,DEAR,LAST_NAME,FIRST_NAME,ADDRESS,CITY_ID,PHONE,AGE,SALES_PERS_ID) values (405,0,'Schultz','Herbert','Am Holzbach 17',55,'256346',59,51);
Insert into SRC_OCIGGLL.SRC_CUSTOMER (CUSTID,DEAR,LAST_NAME,FIRST_NAME,ADDRESS,CITY_ID,PHONE,AGE,SALES_PERS_ID) values (406,0,'Titzman','Silke','Berliner Ring 56',56,'235463',63,52);
Insert into SRC_OCIGGLL.SRC_CUSTOMER (CUSTID,DEAR,LAST_NAME,FIRST_NAME,ADDRESS,CITY_ID,PHONE,AGE,SALES_PERS_ID) values (407,2,'Reinman','Heineke','Yorkstra� 75',55,'234646',72,32);
Insert into SRC_OCIGGLL.SRC_CUSTOMER (CUSTID,DEAR,LAST_NAME,FIRST_NAME,ADDRESS,CITY_ID,PHONE,AGE,SALES_PERS_ID) values (501,0,'Arai','Toshihijo','941 Toyota Ave',70,'34784597',18,40);
Insert into SRC_OCIGGLL.SRC_CUSTOMER (CUSTID,DEAR,LAST_NAME,FIRST_NAME,ADDRESS,CITY_ID,PHONE,AGE,SALES_PERS_ID) values (502,0,'Kamata','Mariko','70 Kiroto Street',71,'57687462',24,41);
Insert into SRC_OCIGGLL.SRC_CUSTOMER (CUSTID,DEAR,LAST_NAME,FIRST_NAME,ADDRESS,CITY_ID,PHONE,AGE,SALES_PERS_ID) values (503,0,'Kamimura','Satoru','34 Kawasaki Avenue',72,'26475684',38,42);
Insert into SRC_OCIGGLL.SRC_CUSTOMER (CUSTID,DEAR,LAST_NAME,FIRST_NAME,ADDRESS,CITY_ID,PHONE,AGE,SALES_PERS_ID) values (504,0,'Makino','Tatsuo','2435 Toyota Ave',70,'34413486',45,50);
Insert into SRC_OCIGGLL.SRC_CUSTOMER (CUSTID,DEAR,LAST_NAME,FIRST_NAME,ADDRESS,CITY_ID,PHONE,AGE,SALES_PERS_ID) values (505,0,'Mukumoto','Masayuki','59 Yamamoto Blvd',73,'34827691',59,51);
Insert into SRC_OCIGGLL.SRC_CUSTOMER (CUSTID,DEAR,LAST_NAME,FIRST_NAME,ADDRESS,CITY_ID,PHONE,AGE,SALES_PERS_ID) values (506,0,'Oneda','Kenji','94 Toyota Blvd',70,'51839463',68,52);
Insert into SRC_OCIGGLL.SRC_CUSTOMER (CUSTID,DEAR,LAST_NAME,FIRST_NAME,ADDRESS,CITY_ID,PHONE,AGE,SALES_PERS_ID) values (507,0,'Okumura','Isao','3 Toyota Ave',74,'48928371',74,21);
commit;
REM INSERTING into SRC_OCIGGLL.SRC_ORDERS
SET DEFINE OFF;
Insert into SRC_OCIGGLL.SRC_ORDERS (ORDER_ID,STATUS,CUST_ID,ORDER_DATE,CUSTOMER) values (1,'COM',1001,to_date('11-JAN-01','DD-MON-RR'),null);
Insert into SRC_OCIGGLL.SRC_ORDERS (ORDER_ID,STATUS,CUST_ID,ORDER_DATE,CUSTOMER) values (2,'CLO',1002,to_date('12-FEB-99','DD-MON-RR'),null);
Insert into SRC_OCIGGLL.SRC_ORDERS (ORDER_ID,STATUS,CUST_ID,ORDER_DATE,CUSTOMER) values (3,'CLO',103,to_date('23-MAR-90','DD-MON-RR'),null);
Insert into SRC_OCIGGLL.SRC_ORDERS (ORDER_ID,STATUS,CUST_ID,ORDER_DATE,CUSTOMER) values (4,'CLO',104,to_date('26-APR-91','DD-MON-RR'),null);
Insert into SRC_OCIGGLL.SRC_ORDERS (ORDER_ID,STATUS,CUST_ID,ORDER_DATE,CUSTOMER) values (5,'COM',105,to_date('10-MAY-98','DD-MON-RR'),null);
Insert into SRC_OCIGGLL.SRC_ORDERS (ORDER_ID,STATUS,CUST_ID,ORDER_DATE,CUSTOMER) values (6,'CLO',106,to_date('23-JUN-98','DD-MON-RR'),null);
Insert into SRC_OCIGGLL.SRC_ORDERS (ORDER_ID,STATUS,CUST_ID,ORDER_DATE,CUSTOMER) values (7,'COM',107,to_date('30-JUL-01','DD-MON-RR'),null);
Insert into SRC_OCIGGLL.SRC_ORDERS (ORDER_ID,STATUS,CUST_ID,ORDER_DATE,CUSTOMER) values (8,'CLO',201,to_date('18-AUG-00','DD-MON-RR'),null);
Insert into SRC_OCIGGLL.SRC_ORDERS (ORDER_ID,STATUS,CUST_ID,ORDER_DATE,CUSTOMER) values (9,'COM',202,to_date('15-SEP-01','DD-MON-RR'),null);
Insert into SRC_OCIGGLL.SRC_ORDERS (ORDER_ID,STATUS,CUST_ID,ORDER_DATE,CUSTOMER) values (10,'CLO',203,to_date('20-MAY-99','DD-MON-RR'),null);
commit;
REM INSERTING into SRC_OCIGGLL.SRC_ORDER_LINES
SET DEFINE OFF;
Insert into SRC_OCIGGLL.SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (1,1,1,549,59292);
Insert into SRC_OCIGGLL.SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (1,2,2,1477,146223);
Insert into SRC_OCIGGLL.SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (1,3,3,1163,20934);
Insert into SRC_OCIGGLL.SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (2,1,4,1689,136809);
Insert into SRC_OCIGGLL.SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (2,2,5,1829,172840.5);
Insert into SRC_OCIGGLL.SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (2,3,6,1932,52164);
Insert into SRC_OCIGGLL.SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (3,1,7,1697,45819);
Insert into SRC_OCIGGLL.SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (3,2,8,1994,44865);
Insert into SRC_OCIGGLL.SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (3,3,9,764,30942);
Insert into SRC_OCIGGLL.SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (4,1,6,1457,39339);
Insert into SRC_OCIGGLL.SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (4,2,11,1197,16159.5);
Insert into SRC_OCIGGLL.SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (4,3,12,830,22410);
Insert into SRC_OCIGGLL.SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (5,1,1,249,26892);
Insert into SRC_OCIGGLL.SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (5,2,3,840,15120);
Insert into SRC_OCIGGLL.SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (5,3,11,1723,23260.5);
Insert into SRC_OCIGGLL.SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (6,1,7,1086,29322);
Insert into SRC_OCIGGLL.SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (6,2,13,1676,7542);
Insert into SRC_OCIGGLL.SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (6,3,14,587,9509.4);
Insert into SRC_OCIGGLL.SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (7,1,3,1196,21528);
Insert into SRC_OCIGGLL.SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (7,2,5,1787,168871.5);
Insert into SRC_OCIGGLL.SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (7,3,6,1523,41121);
Insert into SRC_OCIGGLL.SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (8,1,2,1816,179784);
Insert into SRC_OCIGGLL.SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (8,2,4,1787,144747);
Insert into SRC_OCIGGLL.SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (8,3,10,1493,107496);
Insert into SRC_OCIGGLL.SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9,1,7,510,13770);
Insert into SRC_OCIGGLL.SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9,2,9,1334,54027);
Insert into SRC_OCIGGLL.SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9,3,15,1544,2779.2);
Insert into SRC_OCIGGLL.SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (10,1,4,1552,125712);
Insert into SRC_OCIGGLL.SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (10,2,7,972,26244);
Insert into SRC_OCIGGLL.SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (10,3,9,1999,89955);
commit;
REM INSERTING into SRC_OCIGGLL.SRC_PRODUCT
SET DEFINE OFF;
Insert into SRC_OCIGGLL.SRC_PRODUCT (PRODUCT_ID,PRODUCT,PRICE,FAMILY_NAME) values (1,'Gold Watch',120,'Watches');
Insert into SRC_OCIGGLL.SRC_PRODUCT (PRODUCT_ID,PRODUCT,PRICE,FAMILY_NAME) values (2,'Silver Watch',110,'Watches');
Insert into SRC_OCIGGLL.SRC_PRODUCT (PRODUCT_ID,PRODUCT,PRICE,FAMILY_NAME) values (3,'Earrings',20,'Jewels');
Insert into SRC_OCIGGLL.SRC_PRODUCT (PRODUCT_ID,PRODUCT,PRICE,FAMILY_NAME) values (4,'Gold Bracelet',90,'Jewels');
Insert into SRC_OCIGGLL.SRC_PRODUCT (PRODUCT_ID,PRODUCT,PRICE,FAMILY_NAME) values (5,'Silver Collar',105,'Jewels');
Insert into SRC_OCIGGLL.SRC_PRODUCT (PRODUCT_ID,PRODUCT,PRICE,FAMILY_NAME) values (6,'Green Sweetshirt',30,'Sportswear');
Insert into SRC_OCIGGLL.SRC_PRODUCT (PRODUCT_ID,PRODUCT,PRICE,FAMILY_NAME) values (7,'Red Sweetshirt',30,'Sportswear');
Insert into SRC_OCIGGLL.SRC_PRODUCT (PRODUCT_ID,PRODUCT,PRICE,FAMILY_NAME) values (8,'White Sweetshirt',25,'Sportswear');
Insert into SRC_OCIGGLL.SRC_PRODUCT (PRODUCT_ID,PRODUCT,PRICE,FAMILY_NAME) values (9,'Sport Shoes',45,'Sportswear');
Insert into SRC_OCIGGLL.SRC_PRODUCT (PRODUCT_ID,PRODUCT,PRICE,FAMILY_NAME) values (10,'Tennis Racket',80,'Equipment');
Insert into SRC_OCIGGLL.SRC_PRODUCT (PRODUCT_ID,PRODUCT,PRICE,FAMILY_NAME) values (11,'Tennis Balls',15,'Equipment');
Insert into SRC_OCIGGLL.SRC_PRODUCT (PRODUCT_ID,PRODUCT,PRICE,FAMILY_NAME) values (12,'Sunglasses',30,'Equipment');
Insert into SRC_OCIGGLL.SRC_PRODUCT (PRODUCT_ID,PRODUCT,PRICE,FAMILY_NAME) values (13,'Keyring',5,'Various');
Insert into SRC_OCIGGLL.SRC_PRODUCT (PRODUCT_ID,PRODUCT,PRICE,FAMILY_NAME) values (14,'Towel',18,'Various');
Insert into SRC_OCIGGLL.SRC_PRODUCT (PRODUCT_ID,PRODUCT,PRICE,FAMILY_NAME) values (15,'French Choucroute',2,'Various');
commit;
REM INSERTING into SRC_OCIGGLL.SRC_REGION
SET DEFINE OFF;
Insert into SRC_OCIGGLL.SRC_REGION (REGION_ID,REGION,COUNTRY_ID,COUNTRY) values (20,'South',1,'USA');
Insert into SRC_OCIGGLL.SRC_REGION (REGION_ID,REGION,COUNTRY_ID,COUNTRY) values (21,'West',1,'USA');
Insert into SRC_OCIGGLL.SRC_REGION (REGION_ID,REGION,COUNTRY_ID,COUNTRY) values (22,'East Coast',1,'USA');
Insert into SRC_OCIGGLL.SRC_REGION (REGION_ID,REGION,COUNTRY_ID,COUNTRY) values (23,'Mid West',1,'USA');
Insert into SRC_OCIGGLL.SRC_REGION (REGION_ID,REGION,COUNTRY_ID,COUNTRY) values (30,'Paris',2,'France');
Insert into SRC_OCIGGLL.SRC_REGION (REGION_ID,REGION,COUNTRY_ID,COUNTRY) values (31,'French Alps',2,'France');
Insert into SRC_OCIGGLL.SRC_REGION (REGION_ID,REGION,COUNTRY_ID,COUNTRY) values (32,'Provence',2,'France');
Insert into SRC_OCIGGLL.SRC_REGION (REGION_ID,REGION,COUNTRY_ID,COUNTRY) values (33,'Normandy',2,'France');
Insert into SRC_OCIGGLL.SRC_REGION (REGION_ID,REGION,COUNTRY_ID,COUNTRY) values (40,'Wales',3,'Great Britain');
Insert into SRC_OCIGGLL.SRC_REGION (REGION_ID,REGION,COUNTRY_ID,COUNTRY) values (41,'Scotland',3,'Great Britain');
Insert into SRC_OCIGGLL.SRC_REGION (REGION_ID,REGION,COUNTRY_ID,COUNTRY) values (42,'Northern Ireland',3,'Great Britain');
Insert into SRC_OCIGGLL.SRC_REGION (REGION_ID,REGION,COUNTRY_ID,COUNTRY) values (43,'England',3,'Great Britain');
Insert into SRC_OCIGGLL.SRC_REGION (REGION_ID,REGION,COUNTRY_ID,COUNTRY) values (50,'South Holland',7,'Nederland');
Insert into SRC_OCIGGLL.SRC_REGION (REGION_ID,REGION,COUNTRY_ID,COUNTRY) values (51,'North Holland',7,'Nederland');
Insert into SRC_OCIGGLL.SRC_REGION (REGION_ID,REGION,COUNTRY_ID,COUNTRY) values (60,'Ruhr',4,'Germany');
Insert into SRC_OCIGGLL.SRC_REGION (REGION_ID,REGION,COUNTRY_ID,COUNTRY) values (61,'Bavaria',4,'Germany');
Insert into SRC_OCIGGLL.SRC_REGION (REGION_ID,REGION,COUNTRY_ID,COUNTRY) values (62,'East Germany',4,'Germany');
Insert into SRC_OCIGGLL.SRC_REGION (REGION_ID,REGION,COUNTRY_ID,COUNTRY) values (70,'South Wales',6,'Autralia');
Insert into SRC_OCIGGLL.SRC_REGION (REGION_ID,REGION,COUNTRY_ID,COUNTRY) values (71,'Victoria',6,'Autralia');
Insert into SRC_OCIGGLL.SRC_REGION (REGION_ID,REGION,COUNTRY_ID,COUNTRY) values (72,'Queensland',6,'Autralia');
Insert into SRC_OCIGGLL.SRC_REGION (REGION_ID,REGION,COUNTRY_ID,COUNTRY) values (80,'East Japan',5,'Japan');
Insert into SRC_OCIGGLL.SRC_REGION (REGION_ID,REGION,COUNTRY_ID,COUNTRY) values (81,'West Japan',5,'Japan');
commit;


--------------------------------------------------------
--  DDL for Index PK_SRC_CITY
--------------------------------------------------------

  CREATE UNIQUE INDEX "SRC_OCIGGLL"."PK_SRC_CITY" ON 
 "SRC_OCIGGLL"."SRC_CITY" ("CITY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Index PK_SRC_CUSTOMER
--------------------------------------------------------

  CREATE UNIQUE INDEX "SRC_OCIGGLL"."PK_SRC_CUSTOMER" ON 
"SRC_OCIGGLL"."SRC_CUSTOMER" ("CUSTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Index PK_SRC_ORDERS
--------------------------------------------------------

  CREATE UNIQUE INDEX "SRC_OCIGGLL"."PK_SRC_ORDERS" ON 
"SRC_OCIGGLL"."SRC_ORDERS" ("ORDER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Index PK_SRC_ORDER_LINES
--------------------------------------------------------

  CREATE UNIQUE INDEX "SRC_OCIGGLL"."PK_SRC_ORDER_LINES" ON 
"SRC_OCIGGLL"."SRC_ORDER_LINES" ("LORDER_ID", "ORDER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Index PK_SRC_PRODUCT
--------------------------------------------------------

  CREATE UNIQUE INDEX "SRC_OCIGGLL"."PK_SRC_PRODUCT" ON 
"SRC_OCIGGLL"."SRC_PRODUCT" ("PRODUCT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Index PK_SRC_REGION
--------------------------------------------------------

  CREATE UNIQUE INDEX "SRC_OCIGGLL"."PK_SRC_REGION" ON 
"SRC_OCIGGLL"."SRC_REGION" ("REGION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;


--------------------------------------------------------
--  Constraints for Table SRC_CITY
--------------------------------------------------------

  ALTER TABLE "SRC_OCIGGLL"."SRC_CITY" ADD CONSTRAINT "PK_SRC_CITY" PRIMARY KEY ("CITY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE;
  ALTER TABLE "SRC_OCIGGLL"."SRC_CITY" MODIFY ("CITY_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SRC_CUSTOMER
--------------------------------------------------------

  ALTER TABLE "SRC_OCIGGLL"."SRC_CUSTOMER" ADD CONSTRAINT "PK_SRC_CUSTOMER" PRIMARY KEY ("CUSTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE;
  ALTER TABLE "SRC_OCIGGLL"."SRC_CUSTOMER" MODIFY ("CUSTID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SRC_ORDERS
--------------------------------------------------------

  ALTER TABLE "SRC_OCIGGLL"."SRC_ORDERS" ADD CONSTRAINT "PK_SRC_ORDERS" PRIMARY KEY ("ORDER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE;
  ALTER TABLE "SRC_OCIGGLL"."SRC_ORDERS" MODIFY ("ORDER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SRC_ORDER_LINES
--------------------------------------------------------

  ALTER TABLE "SRC_OCIGGLL"."SRC_ORDER_LINES" ADD CONSTRAINT "PK_SRC_ORDER_LINES" PRIMARY KEY ("LORDER_ID", "ORDER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE;
  ALTER TABLE "SRC_OCIGGLL"."SRC_ORDER_LINES" MODIFY ("LORDER_ID" NOT NULL ENABLE);
  ALTER TABLE "SRC_OCIGGLL"."SRC_ORDER_LINES" MODIFY ("ORDER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SRC_PRODUCT
--------------------------------------------------------

  ALTER TABLE "SRC_OCIGGLL"."SRC_PRODUCT" ADD CONSTRAINT "PK_SRC_PRODUCT" PRIMARY KEY ("PRODUCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE;
  ALTER TABLE "SRC_OCIGGLL"."SRC_PRODUCT" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SRC_REGION
--------------------------------------------------------

  ALTER TABLE "SRC_OCIGGLL"."SRC_REGION" ADD CONSTRAINT "PK_SRC_REGION" PRIMARY KEY ("REGION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE;
  ALTER TABLE "SRC_OCIGGLL"."SRC_REGION" MODIFY ("REGION_ID" NOT NULL ENABLE);

CREATE OR REPLACE PROCEDURE "SRC_OCIGGLL".INSERTDATAWAIT 

(
  MWAIT IN NUMBER 
) AS 

BEGIN
Insert into "SRC_OCIGGLL".SRC_ORDERS (ORDER_ID,STATUS,CUST_ID,ORDER_DATE,CUSTOMER) values (9000,'COM',201,to_date('01-JAN-2020','DD-MON-YYYY'),null);
commit;
--REM INSERTING into "SRC_OCIGGLL".SRC_ORDER_LINES
DBMS_SESSION.SLEEP ( MWAIT);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9000,1,5,731,69079.5);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9000,2,6,1005,27135);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9000,3,10,426,30672);
commit;

Insert into "SRC_OCIGGLL".SRC_ORDERS (ORDER_ID,STATUS,CUST_ID,ORDER_DATE,CUSTOMER) values (9001,'COM',201,to_date('01-JAN-2020','DD-MON-YYYY'),null);
commit;
--REM INSERTING into "SRC_OCIGGLL".SRC_ORDER_LINES
DBMS_SESSION.SLEEP ( MWAIT);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9001,1,5,731,69079.5);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9001,2,6,1005,27135);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9001,3,10,426,30672);
commit;

Insert into "SRC_OCIGGLL".SRC_ORDERS (ORDER_ID,STATUS,CUST_ID,ORDER_DATE,CUSTOMER) values (9002,'COM',201,to_date('01-JAN-2020','DD-MON-YYYY'),null);
commit;
--REM INSERTING into "SRC_OCIGGLL".SRC_ORDER_LINES
DBMS_SESSION.SLEEP ( MWAIT);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9002,1,5,731,69079.5);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9002,2,6,1005,27135);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9002,3,10,426,30672);
commit;
DBMS_SESSION.SLEEP ( MWAIT);
Insert into "SRC_OCIGGLL".SRC_ORDERS (ORDER_ID,STATUS,CUST_ID,ORDER_DATE,CUSTOMER) values (9003,'COM',201,to_date('01-JAN-2020','DD-MON-YYYY'),null);
commit;
--REM INSERTING into "SRC_OCIGGLL".SRC_ORDER_LINES

Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9003,1,5,731,69079.5);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9003,2,6,1005,27135);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9003,3,10,426,30672);
commit;

Insert into "SRC_OCIGGLL".SRC_ORDERS (ORDER_ID,STATUS,CUST_ID,ORDER_DATE,CUSTOMER) values (9004,'COM',201,to_date('01-JAN-2020','DD-MON-YYYY'),null);
commit;
--REM INSERTING into "SRC_OCIGGLL".SRC_ORDER_LINES
DBMS_SESSION.SLEEP ( MWAIT);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9004,1,5,731,69079.5);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9004,2,6,1005,27135);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9004,3,10,426,30672);
commit;

Insert into "SRC_OCIGGLL".SRC_ORDERS (ORDER_ID,STATUS,CUST_ID,ORDER_DATE,CUSTOMER) values (9005,'COM',201,to_date('01-JAN-2020','DD-MON-YYYY'),null);
commit;
--REM INSERTING into "SRC_OCIGGLL".SRC_ORDER_LINES
DBMS_SESSION.SLEEP ( MWAIT);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9005,1,5,731,69079.5);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9005,2,6,1005,27135);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9005,3,10,426,30672);
commit;
update "SRC_OCIGGLL".SRC_ORDERS set ORDER_DATE=to_date('01-DEC-2020','DD-MON-YYYY') where order_id >=9000;
commit;
delete from  "SRC_OCIGGLL".SRC_ORDER_LINES where ORDER_ID=9000 and LORDER_ID=3;
commit;
Insert into "SRC_OCIGGLL".SRC_ORDERS (ORDER_ID,STATUS,CUST_ID,ORDER_DATE,CUSTOMER) values (9006,'COM',201,to_date('01-JAN-2020','DD-MON-YYYY'),null);
commit;
--REM INSERTING into "SRC_OCIGGLL".SRC_ORDER_LINES
DBMS_SESSION.SLEEP ( MWAIT);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9006,1,5,731,69079.5);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9006,2,6,1005,27135);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9006,3,10,426,30672);
commit;

Insert into "SRC_OCIGGLL".SRC_ORDERS (ORDER_ID,STATUS,CUST_ID,ORDER_DATE,CUSTOMER) values (9007,'COM',201,to_date('01-JAN-2020','DD-MON-YYYY'),null);
commit;
--REM INSERTING into "SRC_OCIGGLL".SRC_ORDER_LINES
DBMS_SESSION.SLEEP ( MWAIT);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9007,1,5,731,69079.5);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9007,2,6,1005,27135);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9007,3,10,426,30672);
commit;

Insert into "SRC_OCIGGLL".SRC_ORDERS (ORDER_ID,STATUS,CUST_ID,ORDER_DATE,CUSTOMER) values (9008,'COM',201,to_date('01-JAN-2020','DD-MON-YYYY'),null);
commit;
--REM INSERTING into "SRC_OCIGGLL".SRC_ORDER_LINES
DBMS_SESSION.SLEEP ( MWAIT);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9008,1,5,731,69079.5);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9008,2,6,1005,27135);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9008,3,10,426,30672);
commit;

Insert into "SRC_OCIGGLL".SRC_ORDERS (ORDER_ID,STATUS,CUST_ID,ORDER_DATE,CUSTOMER) values (9009,'COM',201,to_date('01-JAN-2020','DD-MON-YYYY'),null);
commit;
--REM INSERTING into "SRC_OCIGGLL".SRC_ORDER_LINES

Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9009,1,5,731,69079.5);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9009,2,6,1005,27135);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9009,3,10,426,30672);
commit;
DBMS_SESSION.SLEEP ( MWAIT);
Insert into "SRC_OCIGGLL".SRC_ORDERS (ORDER_ID,STATUS,CUST_ID,ORDER_DATE,CUSTOMER) values (9010,'COM',201,to_date('01-JAN-2020','DD-MON-YYYY'),null);
commit;
--REM INSERTING into "SRC_OCIGGLL".SRC_ORDER_LINES

Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9010,1,5,731,69079.5);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9010,2,6,1005,27135);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9010,3,10,426,30672);
commit;

Insert into "SRC_OCIGGLL".SRC_ORDERS (ORDER_ID,STATUS,CUST_ID,ORDER_DATE,CUSTOMER) values (9011,'COM',201,to_date('01-JAN-2020','DD-MON-YYYY'),null);
commit;
--REM INSERTING into "SRC_OCIGGLL".SRC_ORDER_LINES
DBMS_SESSION.SLEEP ( MWAIT);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9011,1,5,731,69079.5);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9011,2,6,1005,27135);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9011,3,10,426,30672);
commit;
update "SRC_OCIGGLL".SRC_ORDERS set ORDER_DATE=to_date('01-DEC-2020','DD-MON-YYYY') where order_id >=9006;
commit;
delete from  "SRC_OCIGGLL".SRC_ORDER_LINES where ORDER_ID=9006 and LORDER_ID=3;
commit;
Insert into "SRC_OCIGGLL".SRC_ORDERS (ORDER_ID,STATUS,CUST_ID,ORDER_DATE,CUSTOMER) values (9012,'COM',201,to_date('01-JAN-2020','DD-MON-YYYY'),null);
commit;
--REM INSERTING into "SRC_OCIGGLL".SRC_ORDER_LINES
DBMS_SESSION.SLEEP ( MWAIT);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9012,1,5,731,69079.5);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9012,2,6,1005,27135);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9012,3,10,426,30672);
commit;

Insert into "SRC_OCIGGLL".SRC_ORDERS (ORDER_ID,STATUS,CUST_ID,ORDER_DATE,CUSTOMER) values (9013,'COM',201,to_date('01-JAN-2020','DD-MON-YYYY'),null);
commit;
--REM INSERTING into "SRC_OCIGGLL".SRC_ORDER_LINES
DBMS_SESSION.SLEEP ( MWAIT);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9013,1,5,731,69079.5);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9013,2,6,1005,27135);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9013,3,10,426,30672);
commit;

Insert into "SRC_OCIGGLL".SRC_ORDERS (ORDER_ID,STATUS,CUST_ID,ORDER_DATE,CUSTOMER) values (9014,'COM',201,to_date('01-JAN-2020','DD-MON-YYYY'),null);
commit;
--REM INSERTING into "SRC_OCIGGLL".SRC_ORDER_LINES
DBMS_SESSION.SLEEP ( MWAIT);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9014,1,5,731,69079.5);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9014,2,6,1005,27135);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9014,3,10,426,30672);
commit;

Insert into "SRC_OCIGGLL".SRC_ORDERS (ORDER_ID,STATUS,CUST_ID,ORDER_DATE,CUSTOMER) values (9015,'COM',201,to_date('01-JAN-2020','DD-MON-YYYY'),null);
commit;
--REM INSERTING into "SRC_OCIGGLL".SRC_ORDER_LINES

Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9015,1,5,731,69079.5);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9015,2,6,1005,27135);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9015,3,10,426,30672);
commit;

Insert into "SRC_OCIGGLL".SRC_ORDERS (ORDER_ID,STATUS,CUST_ID,ORDER_DATE,CUSTOMER) values (9016,'COM',201,to_date('01-JAN-2020','DD-MON-YYYY'),null);
commit;
--REM INSERTING into "SRC_OCIGGLL".SRC_ORDER_LINES
DBMS_SESSION.SLEEP ( MWAIT);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9016,1,5,731,69079.5);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9016,2,6,1005,27135);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9016,3,10,426,30672);
commit;

Insert into "SRC_OCIGGLL".SRC_ORDERS (ORDER_ID,STATUS,CUST_ID,ORDER_DATE,CUSTOMER) values (9017,'COM',201,to_date('01-JAN-2020','DD-MON-YYYY'),null);
commit;
--REM INSERTING into "SRC_OCIGGLL".SRC_ORDER_LINES
DBMS_SESSION.SLEEP ( MWAIT);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9017,1,5,731,69079.5);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9017,2,6,1005,27135);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9017,3,10,426,30672);
commit;
update "SRC_OCIGGLL".SRC_ORDERS set ORDER_DATE=to_date('01-DEC-2020','DD-MON-YYYY') where order_id >=9012;
commit;
delete from  "SRC_OCIGGLL".SRC_ORDER_LINES where ORDER_ID=9012 and LORDER_ID=3;
commit;
Insert into "SRC_OCIGGLL".SRC_ORDERS (ORDER_ID,STATUS,CUST_ID,ORDER_DATE,CUSTOMER) values (9018,'COM',201,to_date('01-JAN-2020','DD-MON-YYYY'),null);
commit;
--REM INSERTING into "SRC_OCIGGLL".SRC_ORDER_LINES
DBMS_SESSION.SLEEP ( MWAIT);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9018,1,5,731,69079.5);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9018,2,6,1005,27135);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9018,3,10,426,30672);
commit;

Insert into "SRC_OCIGGLL".SRC_ORDERS (ORDER_ID,STATUS,CUST_ID,ORDER_DATE,CUSTOMER) values (9019,'COM',201,to_date('01-JAN-2020','DD-MON-YYYY'),null);
commit;
--REM INSERTING into "SRC_OCIGGLL".SRC_ORDER_LINES
DBMS_SESSION.SLEEP ( MWAIT);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9019,1,5,731,69079.5);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9019,2,6,1005,27135);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9019,3,10,426,30672);
commit;

Insert into "SRC_OCIGGLL".SRC_ORDERS (ORDER_ID,STATUS,CUST_ID,ORDER_DATE,CUSTOMER) values (9020,'COM',201,to_date('01-JAN-2020','DD-MON-YYYY'),null);
commit;
--REM INSERTING into "SRC_OCIGGLL".SRC_ORDER_LINES
DBMS_SESSION.SLEEP ( MWAIT);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9020,1,5,731,69079.5);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9020,2,6,1005,27135);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9020,3,10,426,30672);
commit;

Insert into "SRC_OCIGGLL".SRC_ORDERS (ORDER_ID,STATUS,CUST_ID,ORDER_DATE,CUSTOMER) values (9021,'COM',201,to_date('01-JAN-2020','DD-MON-YYYY'),null);
commit;
--REM INSERTING into "SRC_OCIGGLL".SRC_ORDER_LINES

Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9021,1,5,731,69079.5);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9021,2,6,1005,27135);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9021,3,10,426,30672);
commit;
DBMS_SESSION.SLEEP ( MWAIT);
Insert into "SRC_OCIGGLL".SRC_ORDERS (ORDER_ID,STATUS,CUST_ID,ORDER_DATE,CUSTOMER) values (9022,'COM',201,to_date('01-JAN-2020','DD-MON-YYYY'),null);
commit;
--REM INSERTING into "SRC_OCIGGLL".SRC_ORDER_LINES

Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9022,1,5,731,69079.5);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9022,2,6,1005,27135);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9022,3,10,426,30672);
commit;

Insert into "SRC_OCIGGLL".SRC_ORDERS (ORDER_ID,STATUS,CUST_ID,ORDER_DATE,CUSTOMER) values (9023,'COM',201,to_date('01-JAN-2020','DD-MON-YYYY'),null);
commit;
--REM INSERTING into "SRC_OCIGGLL".SRC_ORDER_LINES
DBMS_SESSION.SLEEP ( MWAIT);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9023,1,5,731,69079.5);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9023,2,6,1005,27135);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9023,3,10,426,30672);
commit;
update "SRC_OCIGGLL".SRC_ORDERS set ORDER_DATE=to_date('01-DEC-2020','DD-MON-YYYY') where order_id >=9018;
commit;
delete from  "SRC_OCIGGLL".SRC_ORDER_LINES where ORDER_ID=9018 and LORDER_ID=3;
commit;
Insert into "SRC_OCIGGLL".SRC_ORDERS (ORDER_ID,STATUS,CUST_ID,ORDER_DATE,CUSTOMER) values (9024,'COM',201,to_date('01-JAN-2020','DD-MON-YYYY'),null);
commit;
--REM INSERTING into "SRC_OCIGGLL".SRC_ORDER_LINES

Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9024,1,5,731,69079.5);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9024,2,6,1005,27135);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9024,3,10,426,30672);
commit;

Insert into "SRC_OCIGGLL".SRC_ORDERS (ORDER_ID,STATUS,CUST_ID,ORDER_DATE,CUSTOMER) values (9025,'COM',201,to_date('01-JAN-2020','DD-MON-YYYY'),null);
commit;
--REM INSERTING into "SRC_OCIGGLL".SRC_ORDER_LINES

Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9025,1,5,731,69079.5);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9025,2,6,1005,27135);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9025,3,10,426,30672);
commit;

Insert into "SRC_OCIGGLL".SRC_ORDERS (ORDER_ID,STATUS,CUST_ID,ORDER_DATE,CUSTOMER) values (9026,'COM',201,to_date('01-JAN-2020','DD-MON-YYYY'),null);
commit;
--REM INSERTING into "SRC_OCIGGLL".SRC_ORDER_LINES
DBMS_SESSION.SLEEP ( MWAIT);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9026,1,5,731,69079.5);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9026,2,6,1005,27135);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9026,3,10,426,30672);
commit;

Insert into "SRC_OCIGGLL".SRC_ORDERS (ORDER_ID,STATUS,CUST_ID,ORDER_DATE,CUSTOMER) values (9027,'COM',201,to_date('01-JAN-2020','DD-MON-YYYY'),null);
commit;
--REM INSERTING into "SRC_OCIGGLL".SRC_ORDER_LINES

Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9027,1,5,731,69079.5);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9027,2,6,1005,27135);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9027,3,10,426,30672);
commit;

Insert into "SRC_OCIGGLL".SRC_ORDERS (ORDER_ID,STATUS,CUST_ID,ORDER_DATE,CUSTOMER) values (9028,'COM',201,to_date('01-JAN-2020','DD-MON-YYYY'),null);
commit;
--REM INSERTING into "SRC_OCIGGLL".SRC_ORDER_LINES
DBMS_SESSION.SLEEP ( MWAIT);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9028,1,5,731,69079.5);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9028,2,6,1005,27135);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9028,3,10,426,30672);
commit;

Insert into "SRC_OCIGGLL".SRC_ORDERS (ORDER_ID,STATUS,CUST_ID,ORDER_DATE,CUSTOMER) values (9029,'COM',201,to_date('01-JAN-2020','DD-MON-YYYY'),null);
commit;
--REM INSERTING into "SRC_OCIGGLL".SRC_ORDER_LINES

Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9029,1,5,731,69079.5);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9029,2,6,1005,27135);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9029,3,10,426,30672);
commit;
update "SRC_OCIGGLL".SRC_ORDERS set ORDER_DATE=to_date('01-DEC-2020','DD-MON-YYYY') where order_id >=9024;
commit;
delete from  "SRC_OCIGGLL".SRC_ORDER_LINES where ORDER_ID=9024 and LORDER_ID=3;
commit;
Insert into "SRC_OCIGGLL".SRC_ORDERS (ORDER_ID,STATUS,CUST_ID,ORDER_DATE,CUSTOMER) values (9030,'COM',201,to_date('01-JAN-2020','DD-MON-YYYY'),null);
commit;
--REM INSERTING into "SRC_OCIGGLL".SRC_ORDER_LINES
DBMS_SESSION.SLEEP ( MWAIT);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9030,1,5,731,69079.5);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9030,2,6,1005,27135);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9030,3,10,426,30672);
commit;

Insert into "SRC_OCIGGLL".SRC_ORDERS (ORDER_ID,STATUS,CUST_ID,ORDER_DATE,CUSTOMER) values (9031,'COM',201,to_date('01-JAN-2020','DD-MON-YYYY'),null);
commit;
--REM INSERTING into "SRC_OCIGGLL".SRC_ORDER_LINES

Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9031,1,5,731,69079.5);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9031,2,6,1005,27135);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9031,3,10,426,30672);
commit;

Insert into "SRC_OCIGGLL".SRC_ORDERS (ORDER_ID,STATUS,CUST_ID,ORDER_DATE,CUSTOMER) values (9032,'COM',201,to_date('01-JAN-2020','DD-MON-YYYY'),null);
commit;
--REM INSERTING into "SRC_OCIGGLL".SRC_ORDER_LINES

Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9032,1,5,731,69079.5);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9032,2,6,1005,27135);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9032,3,10,426,30672);
commit;

Insert into "SRC_OCIGGLL".SRC_ORDERS (ORDER_ID,STATUS,CUST_ID,ORDER_DATE,CUSTOMER) values (9033,'COM',201,to_date('01-JAN-2020','DD-MON-YYYY'),null);
commit;
--REM INSERTING into "SRC_OCIGGLL".SRC_ORDER_LINES

Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9033,1,5,731,69079.5);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9033,2,6,1005,27135);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9033,3,10,426,30672);
commit;

Insert into "SRC_OCIGGLL".SRC_ORDERS (ORDER_ID,STATUS,CUST_ID,ORDER_DATE,CUSTOMER) values (9034,'COM',201,to_date('01-JAN-2020','DD-MON-YYYY'),null);
commit;
--REM INSERTING into "SRC_OCIGGLL".SRC_ORDER_LINES

Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9034,1,5,731,69079.5);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9034,2,6,1005,27135);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9034,3,10,426,30672);
commit;

Insert into "SRC_OCIGGLL".SRC_ORDERS (ORDER_ID,STATUS,CUST_ID,ORDER_DATE,CUSTOMER) values (9035,'COM',201,to_date('01-JAN-2020','DD-MON-YYYY'),null);
commit;
--REM INSERTING into "SRC_OCIGGLL".SRC_ORDER_LINES

Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9035,1,5,731,69079.5);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9035,2,6,1005,27135);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9035,3,10,426,30672);
commit;
update "SRC_OCIGGLL".SRC_ORDERS set ORDER_DATE=to_date('01-DEC-2020','DD-MON-YYYY') where order_id >=9030;
commit;
delete from  "SRC_OCIGGLL".SRC_ORDER_LINES where ORDER_ID=9030 and LORDER_ID=3;
commit;
Insert into "SRC_OCIGGLL".SRC_ORDERS (ORDER_ID,STATUS,CUST_ID,ORDER_DATE,CUSTOMER) values (9036,'COM',201,to_date('01-JAN-2020','DD-MON-YYYY'),null);
commit;
--REM INSERTING into "SRC_OCIGGLL".SRC_ORDER_LINES
DBMS_SESSION.SLEEP ( MWAIT);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9036,1,5,731,69079.5);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9036,2,6,1005,27135);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9036,3,10,426,30672);
commit;

Insert into "SRC_OCIGGLL".SRC_ORDERS (ORDER_ID,STATUS,CUST_ID,ORDER_DATE,CUSTOMER) values (9037,'COM',201,to_date('01-JAN-2020','DD-MON-YYYY'),null);
commit;
--REM INSERTING into "SRC_OCIGGLL".SRC_ORDER_LINES

Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9037,1,5,731,69079.5);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9037,2,6,1005,27135);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9037,3,10,426,30672);
commit;

Insert into "SRC_OCIGGLL".SRC_ORDERS (ORDER_ID,STATUS,CUST_ID,ORDER_DATE,CUSTOMER) values (9038,'COM',201,to_date('01-JAN-2020','DD-MON-YYYY'),null);
commit;
--REM INSERTING into "SRC_OCIGGLL".SRC_ORDER_LINES

Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9038,1,5,731,69079.5);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9038,2,6,1005,27135);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9038,3,10,426,30672);
commit;

Insert into "SRC_OCIGGLL".SRC_ORDERS (ORDER_ID,STATUS,CUST_ID,ORDER_DATE,CUSTOMER) values (9039,'COM',201,to_date('01-JAN-2020','DD-MON-YYYY'),null);
commit;
--REM INSERTING into "SRC_OCIGGLL".SRC_ORDER_LINES

Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9039,1,5,731,69079.5);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9039,2,6,1005,27135);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9039,3,10,426,30672);
commit;

Insert into "SRC_OCIGGLL".SRC_ORDERS (ORDER_ID,STATUS,CUST_ID,ORDER_DATE,CUSTOMER) values (9040,'COM',201,to_date('01-JAN-2020','DD-MON-YYYY'),null);
commit;
--REM INSERTING into "SRC_OCIGGLL".SRC_ORDER_LINES
DBMS_SESSION.SLEEP ( MWAIT);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9040,1,5,731,69079.5);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9040,2,6,1005,27135);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9040,3,10,426,30672);
commit;

Insert into "SRC_OCIGGLL".SRC_ORDERS (ORDER_ID,STATUS,CUST_ID,ORDER_DATE,CUSTOMER) values (9041,'COM',201,to_date('01-JAN-2020','DD-MON-YYYY'),null);
commit;
--REM INSERTING into "SRC_OCIGGLL".SRC_ORDER_LINES

Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9041,1,5,731,69079.5);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9041,2,6,1005,27135);
Insert into "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9041,3,10,426,30672);
commit;
update "SRC_OCIGGLL".SRC_ORDERS set ORDER_DATE=to_date('01-DEC-2020','DD-MON-YYYY') where order_id >=9036;
commit;
delete from  "SRC_OCIGGLL".SRC_ORDER_LINES where ORDER_ID=9036 and LORDER_ID=3;
commit;


END INSERTDATAWAIT;

/

CREATE OR REPLACE PROCEDURE "SRC_OCIGGLL".DELETEDATA AS 
BEGIN
delete from  "SRC_OCIGGLL".SRC_ORDERS where ORDER_ID>100;
delete from  "SRC_OCIGGLL".SRC_ORDER_LINES where ORDER_ID>100;
commit;

END DELETEDATA;
/

create or replace PROCEDURE                    "SRC_OCIGGLL".INSERTINITDAT

 AS 

BEGIN
Insert into  "SRC_OCIGGLL".SRC_ORDERS (ORDER_ID,STATUS,CUST_ID,ORDER_DATE,CUSTOMER) values (9041,'COM',201,to_date('01-JAN-2020','DD-MON-YYYY'),null);
commit;
--REM INSERTING into "OCIGGS_SRC_USER".SRC_ORDER_LINES
Insert into  "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9041,1,5,731,69079.5);
Insert into  "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9041,2,6,1005,27135);
Insert into  "SRC_OCIGGLL".SRC_ORDER_LINES (ORDER_ID,LORDER_ID,PRODUCT_ID,QTY,AMOUNT) values (9041,3,10,426,30672);
commit;
update  "SRC_OCIGGLL".SRC_ORDERS set ORDER_DATE=to_date('01-DEC-2020','DD-MON-YYYY') where order_id >=9036;
commit;
delete from   "SRC_OCIGGLL".SRC_ORDER_LINES where ORDER_ID=9036 and LORDER_ID=3;
commit;

delete from   "SRC_OCIGGLL".SRC_ORDERS where ORDER_ID>100;
delete from   "SRC_OCIGGLL".SRC_ORDER_LINES where ORDER_ID>100;
commit;

END INSERTINITDAT;
/

exit