CREATE USER aq_admin IDENTIFIED BY WElcome##123 DEFAULT TABLESPACE users TEMPORARY TABLESPACE temp;
ALTER USER aq_admin QUOTA UNLIMITED ON users;
GRANT aq_administrator_role TO aq_admin;
GRANT connect, resource TO aq_admin;
GRANT create type TO aq_admin;
grant execute on DBMS_AQ to aq_admin;


CREATE USER aq_user IDENTIFIED BY WElcome##123 DEFAULT TABLESPACE users TEMPORARY TABLESPACE temp;
--grant roles to aq_user
GRANT aq_user_role TO aq_user; 



CREATE USER "SRC_OCIGGLL" IDENTIFIED BY "WElcome##123";

GRANT CREATE SESSION TO "SRC_OCIGGLL";

ALTER USER "SRC_OCIGGLL" ACCOUNT UNLOCK;

GRANT CONNECT, RESOURCE  TO "SRC_OCIGGLL";

GRANT UNLIMITED TABLESPACE TO "SRC_OCIGGLL";



--------------------------------------------------------
--  File created - @dsgray 3-07-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SRC_CITY
--------------------------------------------------------

  CREATE TABLE "SRC_OCIGGLL"."SRC_CITY" 
   (	"CITY_ID" NUMBER(10,0), 
	"CITY" VARCHAR2(50 BYTE), 
	"REGION_ID" NUMBER(10,0), 
	"POPULATION" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Table SRC_CUSTOMER
--------------------------------------------------------

  CREATE TABLE "SRC_OCIGGLL"."SRC_CUSTOMER" 
   (	"CUSTID" NUMBER(10,0), 
	"DEAR" NUMBER(1,0), 
	"LAST_NAME" VARCHAR2(50 BYTE), 
	"FIRST_NAME" VARCHAR2(50 BYTE), 
	"ADDRESS" VARCHAR2(100 BYTE), 
	"CITY_ID" NUMBER(10,0), 
	"PHONE" VARCHAR2(50 BYTE), 
	"AGE" NUMBER(3,0), 
	"SALES_PERS_ID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Table SRC_ORDERS
--------------------------------------------------------

  CREATE TABLE "SRC_OCIGGLL"."SRC_ORDERS" 
   (	"ORDER_ID" NUMBER(10,0), 
	"STATUS" VARCHAR2(3 BYTE), 
	"CUST_ID" NUMBER(10,0), 
	"ORDER_DATE" DATE, 
	"CUSTOMER" VARCHAR2(35 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Table SRC_ORDER_LINES
--------------------------------------------------------

  CREATE TABLE "SRC_OCIGGLL"."SRC_ORDER_LINES" 
   (	"ORDER_ID" NUMBER(10,0), 
	"LORDER_ID" NUMBER(10,0), 
	"PRODUCT_ID" NUMBER(10,0), 
	"QTY" NUMBER(10,0), 
	"AMOUNT" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Table SRC_PRODUCT
--------------------------------------------------------

  CREATE TABLE "SRC_OCIGGLL"."SRC_PRODUCT" 
   (	"PRODUCT_ID" NUMBER(10,0), 
	"PRODUCT" VARCHAR2(50 BYTE), 
	"PRICE" NUMBER(10,2), 
	"FAMILY_NAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Table SRC_REGION
--------------------------------------------------------

  CREATE TABLE "SRC_OCIGGLL"."SRC_REGION" 
   (	"REGION_ID" NUMBER(10,0), 
	"REGION" VARCHAR2(50 BYTE), 
	"COUNTRY_ID" NUMBER(10,0), 
	"COUNTRY" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

--------------------------------------------------------
--  DDL for Index PK_SRC_CITY
--------------------------------------------------------

  CREATE UNIQUE INDEX "SRC_OCIGGLL"."PK_SRC_CITY" ON 
 "SRC_OCIGGLL"."SRC_CITY" ("CITY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Index PK_SRC_CUSTOMER
--------------------------------------------------------

  CREATE UNIQUE INDEX "SRC_OCIGGLL"."PK_SRC_CUSTOMER" ON 
"SRC_OCIGGLL"."SRC_CUSTOMER" ("CUSTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Index PK_SRC_ORDERS
--------------------------------------------------------

  CREATE UNIQUE INDEX "SRC_OCIGGLL"."PK_SRC_ORDERS" ON 
"SRC_OCIGGLL"."SRC_ORDERS" ("ORDER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Index PK_SRC_ORDER_LINES
--------------------------------------------------------

  CREATE UNIQUE INDEX "SRC_OCIGGLL"."PK_SRC_ORDER_LINES" ON 
"SRC_OCIGGLL"."SRC_ORDER_LINES" ("LORDER_ID", "ORDER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Index PK_SRC_PRODUCT
--------------------------------------------------------

  CREATE UNIQUE INDEX "SRC_OCIGGLL"."PK_SRC_PRODUCT" ON 
"SRC_OCIGGLL"."SRC_PRODUCT" ("PRODUCT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Index PK_SRC_REGION
--------------------------------------------------------

  CREATE UNIQUE INDEX "SRC_OCIGGLL"."PK_SRC_REGION" ON 
"SRC_OCIGGLL"."SRC_REGION" ("REGION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;


--------------------------------------------------------
--  Constraints for Table SRC_CITY
--------------------------------------------------------

  ALTER TABLE "SRC_OCIGGLL"."SRC_CITY" ADD CONSTRAINT "PK_SRC_CITY" PRIMARY KEY ("CITY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE;
  ALTER TABLE "SRC_OCIGGLL"."SRC_CITY" MODIFY ("CITY_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SRC_CUSTOMER
--------------------------------------------------------

  ALTER TABLE "SRC_OCIGGLL"."SRC_CUSTOMER" ADD CONSTRAINT "PK_SRC_CUSTOMER" PRIMARY KEY ("CUSTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE;
  ALTER TABLE "SRC_OCIGGLL"."SRC_CUSTOMER" MODIFY ("CUSTID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SRC_ORDERS
--------------------------------------------------------

  ALTER TABLE "SRC_OCIGGLL"."SRC_ORDERS" ADD CONSTRAINT "PK_SRC_ORDERS" PRIMARY KEY ("ORDER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE;
  ALTER TABLE "SRC_OCIGGLL"."SRC_ORDERS" MODIFY ("ORDER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SRC_ORDER_LINES
--------------------------------------------------------

  ALTER TABLE "SRC_OCIGGLL"."SRC_ORDER_LINES" ADD CONSTRAINT "PK_SRC_ORDER_LINES" PRIMARY KEY ("LORDER_ID", "ORDER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE;
  ALTER TABLE "SRC_OCIGGLL"."SRC_ORDER_LINES" MODIFY ("LORDER_ID" NOT NULL ENABLE);
  ALTER TABLE "SRC_OCIGGLL"."SRC_ORDER_LINES" MODIFY ("ORDER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SRC_PRODUCT
--------------------------------------------------------

  ALTER TABLE "SRC_OCIGGLL"."SRC_PRODUCT" ADD CONSTRAINT "PK_SRC_PRODUCT" PRIMARY KEY ("PRODUCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE;
  ALTER TABLE "SRC_OCIGGLL"."SRC_PRODUCT" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SRC_REGION
--------------------------------------------------------

  ALTER TABLE "SRC_OCIGGLL"."SRC_REGION" ADD CONSTRAINT "PK_SRC_REGION" PRIMARY KEY ("REGION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE;
  ALTER TABLE "SRC_OCIGGLL"."SRC_REGION" MODIFY ("REGION_ID" NOT NULL ENABLE);


exit